### ISSUE TITLE
Minecolonies - Builder is a lazy thief

### ISSUE THREAD

**Issue by slowiu06** [kreezxil/better-than-minecolonies-getting-started#10]
I have to give him nearly all resources twice. He can't complete some buildings (glass panes, which he wants over and over - hut with 12 panes used 2 stacks of them and It wasn't complete). He is very bugged.

**Comment by kreezxil** [comment]
please post this to the minecolonies tracker at
https://github.com/ldtteam/minecolonies

**Comment by slowiu06** [comment]
Sure, but they have some many issues now, that I'm not sure mine will be visible at all xD

**Comment by slowiu06** [comment]
I got a response, they are already working to fix that issue.

**Comment by kreezxil** [comment]
possibly fixed in todays patch, reopen if still an issue with a new ticket
