### ISSUE TITLE
Silnet Gems went crazy / Need more speed

### ISSUE THREAD

**Issue by slowiu06** [kreezxil/better-than-minecolonies-getting-started#11]
From latest patch, some items which shouldn't be parts have descriptions like tool parts. Of course, nothing can be created, but it looks confusing. 
![2019-10-26_22 15 52](https://user-images.githubusercontent.com/7887594/67625406-40c7af80-f83e-11e9-96e3-9afb9bb4774b.png)

Due to removing of Must go Faster! There is a need of faster travelling method. I don't know when MgF! dev update his mod so I found alternative.
https://www.curseforge.com/minecraft/mc-mods/travellers-boots

**Comment by slowiu06** [comment]
On the other hand some Gems lost their tooltips.
![2019-10-26_22 42 25](https://user-images.githubusercontent.com/7887594/67625728-ffd19a00-f841-11e9-9718-128a56fc932e.png)

**Comment by slowiu06** [comment]
There is a weird problem with vanilla running. My camera twitches what makes running harder.

**Comment by kreezxil** [comment]
honestly you don't need a faster traveling option. You need to join WORD OF
DRAGONS - A NEW AGE. A pack based on that which is getting some heavy play
right now. You'll quickly see that moving quickly thru the game landscape
causes intense server lag.

The same will be true in this pack. Right now it's just you and you don't
notice. Also, Curio of Undying is coming out. it's a POS mod, it causes
loads of problems.

**Comment by slowiu06** [comment]
I'm not a fan of kitchen-sink modpacks, so World of Dragons - New Age is not for me (I never played World of Dragons longer for the same reason. When mixed with Mine&Slash, which needs TONS of proper configurations to suit this type of modpack I'm sure this won't work as I like). 
I was trying using Elytra to move around but I can't due to, like you said - lags. This is the only reason for me wanting better type of boots - Elytra lags AF. 
I don't mind Curio of Undying so much, If it's bad, then just remove it, atm I don't need to use it anyway.

**Comment by kreezxil** [comment]
let's keep reports separated by issue and not stick them all in one. I'll add travellers boots.
