### ISSUE TITLE
Little things and big dreams

### ISSUE THREAD

**Issue by slowiu06** [kreezxil/better-than-minecolonies-getting-started#13]
I have some recommendations for mods - all are QOL type and really well suits whole modpack content.
https://www.curseforge.com/minecraft/mc-mods/colytra - Curio Elytra was deleted. Propably it was a reason of fly-lags which now disappeared.
https://www.curseforge.com/minecraft/mc-mods/easy-elytra-takeoff - Fly like a butterfly.
https://www.curseforge.com/minecraft/mc-mods/better-than-mending - It should be vanilla thing I think.
https://www.curseforge.com/minecraft/mc-mods/structure-compass  **OR/AND** https://www.curseforge.com/minecraft/mc-mods/natures-compass - I cannot find any desert/jungle temples (20k walk wasn't enough, becouse Biomes o Plenty make them muuuuch rarer), but I need to find them soooo much to get Enigmatic Legacy items. 

On the other hand Computer Craft don't suit this modpack. I can tell the same about RFtools. Why? All mods except these two are medieval/non-techy. **(It is only my opinion)**

BTW. For now It's one of the coolest modpack I ever played. I don't know why there aren't more players.

**Comment by slowiu06** [comment]
https://www.curseforge.com/minecraft/mc-mods/demagnetize - Frequent taking off rings is bad for fingers.

**Comment by kreezxil** [comment]
I know you're on my discord, if you go to the bot section you can tell what
they're playing. They're playing World of Dragons - A New Age. You know why
I deleted curiouselytra. I'll add it back tho. that curio of undying will
not come back tho, that was utter garbage code in it.

**Comment by slowiu06** [comment]
Forget about Curio of Undying, If CuriousElytra is lagging forget about it too. Colytra is developed much longer, so I tought that there will be less problems with it.

**Comment by kreezxil** [comment]
there's loads of problems with nearly everything 1.14, the code base is entirely different. the language is still the same but that hardly helps.

removed computer craft and rf tools

other stuff added, we'll see how it pans out, tweet, snapchat, tiktok your friends and followers to play this pack. :)
