### ISSUE TITLE
Structure compass missing recipes

### ISSUE THREAD

**Issue by slowiu06** [kreezxil/better-than-minecolonies-getting-started#14]
I wasn't know that mod developer haven't added recipes for each compass. So if it's possible to add them for all compasses except Stronghold and Burried Treasure (because I don't want to break vanilla mechanics there) would be cool.
It could be even cycle-recipe from one compass to another.

PS. I don't use twitter, snapchat or tiktok. But I'll try to advertise this modpack in other ways.

**Comment by kreezxil** [comment]
The mod is so popular that I am the first issue reported. 

https://github.com/Mrbysco/StructureCompass/issues/1

I'll have an update later this evening TEXAS TIME literally GMT -6 that fixes these recipes.

**Comment by kreezxil** [comment]
fixed by adding my own recipes with drp
