### ISSUE TITLE
Not good at all

### ISSUE THREAD

**Issue by slowiu06** [kreezxil/better-than-minecolonies-getting-started#15]
https://www.curseforge.com/minecraft/mc-mods/nophantomnocry
This mod prevents from getting Phantom Membranes which are needed to some recipes.

**Comment by CriswellCodes** [comment]
Can we add a recipe for phantom membranes like you did for ores Kreezxil?

**Comment by kreezxil** [comment]
I'll add a recipe using drp to get them.
