### ISSUE TITLE
Disable entity radar outside of minimap?

### ISSUE THREAD

**Issue by nekatu** [kreezxil/better-than-minecolonies-getting-started#22]
Hey,

Loving the modpack so far- but I'm finding the psychedelic colors on the entity radar a bit much for my players. Is there a way to disable this?

Thanks!

**Comment by kreezxil** [comment]
which version of the pack are you referring to?

I assume you're talking about Xaero's Minimap which appears as a square in
the upper right and the answer would be yes. Hit 'y' key to access it
settings, there you can find colors and there you can do something to them.

I would also suggest you include a screen shot of what you're talking
about, because other than red and  yellow dots on the minimap, I've no idea
what you mean by psychadelic.

**Comment by nekatu** [comment]
1.25.26 of "Better than Minecolonies Getting Started"

I mean the radar / heat signature type view of all entities in the main game view rather than the minimap. I came across the entity radar options in the minimap but that didn't make a difference, unfortunately.

![2020-02-15_14 35 26](https://user-images.githubusercontent.com/1908371/74589807-9350f580-5000-11ea-88e3-23c84dc742fc.png)
![2020-02-15_14 35 41](https://user-images.githubusercontent.com/1908371/74589808-93e98c00-5000-11ea-9f74-e299553d66e5.png)

**Comment by kreezxil** [comment]
I believe that Apotheosis is causing that effect. There is an entity as I
understand it that is causing that effect on all the surrounding entities.

Now that we know what is going on, I'll double check to see if I can
disable that, and if I can't, Apotheosis will be removed from the next
patch.

**Comment by kreezxil** [comment]
I'm wrong it's probably not Apotheosis. And without ruining the pack I will need to create a new mod that will intercept visual effects and allow mod pack devs/clients to turn them off.

**Comment by nekatu** [comment]
Thanks- it seems to be an effect that disappears after a while, and doesn't even apply to all entities; so maybe something that can be left as is. Was just odd as I couldn't see anything in the list that would be doing it.

**Comment by kreezxil** [comment]
I think it's being caused by The Endergetic Expansion, so that is removed from the pack now, if this continues to happen, open another ticket.
