### ISSUE TITLE
Unkillable Boss

### ISSUE THREAD

**Issue by Mstevens24** [kreezxil/better-than-minecolonies-getting-started#24]
![2020-04-30_14 41 30](https://user-images.githubusercontent.com/64609627/80747607-b6fce580-8af1-11ea-9d8f-e1244d7317ad.png)

Ran into these guys a few times. They are super fast and one hit me. This guy however just shoots arrows which is why I survived long enough to take a screenshot. They are always in diamond armor and I cant even damage them.  They also always have a two part name like a first and a last.

I walled one in once and was able to hit it without it hitting me and it was unkillable. Also put a lava pit and it just sat in there. Only way I killed it was using an admin command.

**Comment by kreezxil** [comment]
This sucks. The mob has a randomly generated name. 
![image](https://user-images.githubusercontent.com/3880072/80752334-efe88a80-8af0-11ea-888a-e9c0e9666ced.png)

**Comment by kreezxil** [comment]
since we haven't identified this mod yet, today's update will have it in there likely

**Comment by toruPuchuu** [comment]
I believe that this is  an Apotheosis Boss Monster. And they walk on water and lava. PITA

**Comment by kreezxil** [comment]
hmm, can you point to a resource as to why you think it is. I need to know for sure.

**Comment by toruPuchuu** [comment]
From the [Apotheosis Forge page](https://www.curseforge.com/minecraft/mc-mods/apotheosis):

Boss Monsters

A boss monster is indicated by a custom name, higher than average stats, and full gear.  When slain, a boss will drop a powerfully enchanted item they were previously wielding.  Additionally, bosses have CraftTweaker support.  Using CraftTweaker, the possible armor sets and available enchantments can be configured.  See the docs for more info. 

and config/apotheosis/deadly.cfg. Regen up to 28!!

**Comment by kreezxil** [comment]
nice, thank you.

**Comment by Mstevens24** [comment]
Wow, so basically one on one I dont have a chance bymyself. I tried again using silent gear and although I healed off any damage they did I also couldnt damage the boss either. Interesting.

**Comment by kreezxil** [comment]
now that we know which mod it is, we might be able to disable it or nerf it somewhat.

**Comment by kreezxil** [comment]
bosses will be drastically easier to kill on next patch release. I found the config in apotheosis that controls it. I hard received the config from the player that originally asked for this mod back when no one was playing the pack. The player ofcourse is no longer playing the pack. So it makes sense to default it for the better enjoyment of all.
