### ISSUE TITLE
Minecolonies

### ISSUE THREAD

**Issue by Mstevens24** [kreezxil/better-than-minecolonies-getting-started#26]
Noticed that the minecolonies mod isnt updated. I dont have access to the hospital or university block. Is there any way to update to this?

**Comment by kreezxil** [comment]
Grok answered you. If you're playing single player, just go ahead and update the mod or mods that are outdated. But when you do, you are in your own area.

But since you have made a bug report, that tells me someone is playing this pack and therefore I will update it.

**Comment by Mstevens24** [comment]
He said to make a request, thought this was the spot to do it since I saw that other people had also used this area to make requests as well.

**Comment by GrokDuckFarmer** [comment]
Kreezxil, he mentioned that he's hosting his own server in chat.  For stability, letting you know that MC has an update for an official update to the modpack is better than hoping it can be dropped in without issues onto his server.

**Comment by kreezxil** [comment]
either way I said i would update this. :)

**Comment by kreezxil** [comment]
Oh the reason this is better than the Discord, is because in Discord the requests scroll into obliviion and hardly anyone takes note.

**Comment by kreezxil** [comment]
if nothing wonky happens there will be an update out sometime in the next 6 hours.
