### ISSUE TITLE
Legal duping and balance

### ISSUE THREAD

**Issue by slowiu06** [kreezxil/better-than-minecolonies-getting-started#3]
![2019-10-19_01 51 11](https://user-images.githubusercontent.com/7887594/67134558-0e50fd80-f213-11e9-905a-470acdc6fc5c.png)
MCFurnace generators allows to infinite resources.

**Comment by slowiu06** [comment]
You have to do something with Silent Gems balance. My Aquamarine, Alexandrite, Phospophylite (with iron rod, gilded bowstring, and redstone upgrade) bow and crossbow deals 24 damage to iron golem. It's unenchanted and made with common resources. With this setup damage should be  about half of this. I think if we count Apotheosis, one-shotting Wither is more than possible.
On the other hand, Ultimate boots from Boots mod looks pretty OP.

**Comment by kreezxil** [comment]
@raphtio i agree with AtomicStryker you need to stop piggybacking. make a
separate issue for each idea.

**Comment by kreezxil** [comment]
I'm removing this mod as a solution. The mod author hasn't even logged on to CurseForge for 6 days now.
