### ISSUE TITLE
Another duping (by my fault) and some toughts

### ISSUE THREAD

**Issue by slowiu06** [kreezxil/better-than-minecolonies-getting-started#6]
ZmodSkills, which is really funny but allows to make endless block resources (iron, gold). I don't think it should be deleted but all "X"lotterysetting.json should be cleared. Only benefit left from leveling will be mining/digging speed and additional grind/farm resources what is good, until developer change this behavior. It'll still allows do dupe wood, but speed of this is similar to normal chopping trees.

Must Go Faster, I found weird behavior. 1st It doens't have a config file so... you know. We can enchant all armour parts, weapons, tools, and even cookies and more with with both, Step Assist and Speed (up to 5th lvl) what is ridiculous. I tought only boots are enchantable, but was wrong. I was looking for other mods with step assist, but none of them have it as enchantment ;/

MoreBoots, It's waaaaaaaaaaaay too overpowered. I've seen comments on curse where people was asking for config file or reduce it's strenght, but for now just look at screenshot (all buffs comes from ultimate version of this boots)
![2019-10-20_19 58 57](https://user-images.githubusercontent.com/7887594/67232426-9f0d2080-f441-11e9-8aaf-553edc88d29e.png)

InfernalMobs just need some changes in configs. There is an option to incrase base mob hp, multipling it by 1.2-1.6 sounds fine. There are few mods which are very annoying and could be turned off: 
Webber - spawns Webs at the Players legs (it works from distance even when mobs are far away)
Vengeance - reflects a portion of all damage done (with high damage it can easly kill us, because it doesn't count defences)
Sticky - can snatch Items the Player attacks them with (I hate it)
Rust - causes high amounts of wear on weapons and armour when fought
Gravity - knocks back or pulls Players (it works from distance even when mobs are far away)
Blastoff - Tosses Players into the air (not so bad in Overworld, but elsewhere...)
They wouldn't be so annoying, but they are working even when we lost contact with an enemy.

With the Curio of undying I don't understand posted code enough. I was sure it only allows us to hold totem in curio slot instead of Left (shield)/Right(hotbar) hand.

**Comment by slowiu06** [comment]
Just realized that InfernalMobs is not compatible with Apotheosis bosses and makes them immortal in some cases. Some combinations are just unkillable, because bosses changes their stages over and over. 
So if It's not a problem I think InfernalMobs should be removed. There are too many problems with it.

**Comment by kreezxil** [comment]
infernalmobs or apotheosis?

**Comment by slowiu06** [comment]
InfernalMobs.

**Comment by kreezxil** [comment]
all notes have been applied. 

you know, step assist is pointless, because that's what "auto jump" is in the keybinds.
