### ISSUE TITLE
Recipe conflict

### ISSUE THREAD

**Issue by slowiu06** [kreezxil/better-than-minecolonies-getting-started#8]
Recipes comes from Mo'Blocks mod.
![Przechwytywanie2](https://user-images.githubusercontent.com/7887594/67509274-ee965b00-f692-11e9-9b9f-22779772478e.PNG)
![Przechwytywanie](https://user-images.githubusercontent.com/7887594/67509275-ef2ef180-f692-11e9-841f-6748a3bd58b3.PNG)

Vertical slabs and pillars have the same recipe.

**Comment by kreezxil** [comment]
ok, I'll report it and then modify "better with minecolonies" to correct that.

**Comment by kreezxil** [comment]
filed at https://www.curseforge.com/minecraft/mc-mods/moblocks/issues/1

**Comment by kreezxil** [comment]
ok, i just looked at how serious this is and it's bad, too many recipes for me to compensate for with my own pack, we'll have to wait on the moblocks author to fix them. Also that means this will not go into WOD - A NEW AGE

**Comment by kreezxil** [comment]
fixed with my own recipes using drp.
