### ISSUE TITLE
Too many building tools

### ISSUE THREAD

**Issue by slowiu06** [kreezxil/better-than-minecolonies-getting-started#9]
There is:
- RFToolsBuilder (a bit broken if used as Quarry, it mines unbelievable fast ( few stacks per second) when pre-powered), building bart is useless when compared to Schematicannon
- BuidingGadgets (pretty useless like above)
- Structurize (Minecolonies), needed "AF"
- Schematicannon (Create), I love it, It's so balanced and easy to use. My best friend now.

Is not it too much?

**Comment by kreezxil** [comment]
We need to get these results to those mod authors. As such information can
help further the cause.

**Comment by slowiu06** [comment]
needlessly added "AF" to structurize, I meant it is very needed

**Comment by kreezxil** [comment]
yes, structurize is a library mod for minecolonies, you can't escape that
one.

**Comment by kreezxil** [comment]
ok, i slowed the quarry way way way down.
It's always good to have more than one builder mod, gonna keep the building gadgets and rftools builder. Not everyone likes to where the same type of underwear.
